### ISSUE TITLE
Data error

### ISSUE THREAD

**Issue by kamao** [flakshack/SysAdminBoard#6]
Hi

Just looking to get this up and running in a vmware lab environment and having some issues pulling data despite connecting successfully.
![dataerror](https://cloud.githubusercontent.com/assets/21205673/22396534/e4cab39e-e553-11e6-903e-b825f54f619e.PNG)

I've probably missed something but any info would be appreciated?
CentOS 6.8, vCenter/ESXi 6.0u2

**Comment by flakshack** [comment]
Unfortunately I haven't tested it against anything other than ESX 5.5.  I would assume that the VMware APIs should work the same though.

The problem seems to be occurring in vmware_host.py somewhere after line 143.  My guess is that if you try running the module by itself if will output additional error information that might be helpful.

**Comment by kamao** [comment]
That will be it, 2 hosts in the vCenter and second one was off (lab).. everything looks good once the other host was powered up.
Thanks for coming back!! :)
